name: Create new release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Semantic versioning release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set git identity
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Build files
        run: |
          npm install
          npm run build:bundles

      # Increments the version number, creates git commit, and git tag.
      - name: Increment version
        run: |
          npm version ${{inputs.release_type}}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Get new package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{steps.package-version.outputs.current-version}}
          files: |
            dist/bundle.css
            dist/bundle.js
